// ==========================================
// Built-in World Book Entries (Developer Only)
// ==========================================
// Built-in world book content is obfuscated only to reduce casual source viewing; it is not a security boundary.
// 说明：
// 1. 这里的条目内容不会出现在用户可见的世界书 UI 中
// 2. 内置条目正文存放在下方编码 payload 中，运行时解码后注入
// 3. 书只是容器，真正生效的是条目本身
// 4. 每个条目都支持：触发机制、注入位置、系统深度、顺序、递归开关

window.normalizeWorldBookEntry = function(entry = {}) {
    return {
        id: entry.id || `wb-entry-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        title: entry.title || entry.name || '未命名词条',
        keyword: entry.keyword || '',
        content: entry.content || '',
        triggerMode: entry.triggerMode === 'keyword' ? 'keyword' : 'permanent',
        injectionPosition: ['before_role', 'after_role', 'system_depth'].includes(entry.injectionPosition)
            ? entry.injectionPosition
            : 'before_role',
        systemDepth: Number.isFinite(Number(entry.systemDepth)) ? Number(entry.systemDepth) : 4,
        order: Number.isFinite(Number(entry.order)) ? Number(entry.order) : 100,
        recursive: false,
        enabled: entry.enabled !== false
    };
};

window.worldBookKeywordMatched = function(entry, contextText = '') {
    if (!entry || entry.triggerMode !== 'keyword') return true;

    const keyword = entry.keyword ? String(entry.keyword).trim() : '';
    if (!keyword) return false;

    const keywords = keyword
        .split(/[，,、]/)
        .map(item => item.trim())
        .filter(Boolean);

    if (!keywords.length) return false;

    const haystack = String(contextText || '');
    return keywords.some(item => haystack.includes(item));
};

window.formatWorldBookEntryForPrompt = function(entry) {
    const title = entry.title ? String(entry.title).trim() : '未命名词条';
    const keyword = entry.keyword ? String(entry.keyword).trim() : '';
    const content = entry.content ? String(entry.content).trim() : '';
    const triggerModeLabel = entry.triggerMode === 'keyword' ? '关键词' : '永久';

    let injectionLabel = '角色前';
    if (entry.injectionPosition === 'after_role') injectionLabel = '角色后';
    if (entry.injectionPosition === 'system_depth') injectionLabel = '系统深度';

    let block = `【${title}】\n`;
    block += `触发机制: ${triggerModeLabel}\n`;
    block += `注入位置: ${injectionLabel}\n`;

    if (entry.injectionPosition === 'system_depth') {
        block += `深度: ${entry.systemDepth}\n`;
        block += `顺序: ${entry.order}\n`;
    }

    if (entry.triggerMode === 'keyword' && keyword) {
        block += `关键词: ${keyword}\n`;
    }

    if (content) {
        block += `内容:\n${content}\n`;
    }

    return block.trim();
};

const BUILTIN_WB_XOR_KEY = 'u2-builtin-worldbook-mask';
const BUILTIN_WB_PAYLOAD = [
    'LkkPCxFLVlYLG0QbGxsCSQ4GGQJDCkwFAhdXAFNYWU5YSxpEAwMXTl5AidvQydfble/qAwNSV0VOHwwXWhgdFk5eQE1DSU4C',
    'DwcOG0YPWFdViujph4bvif7rgNnLUTdDMQ9QSy56ZCU9STwmICF/PjsrTDc7PDsuYE0zJicwYXA+GzUCV0pObhgdFzAKPgEC',
    'DlkMWy8FVRJJBwYKHh0ZGkQYAUhMPQ0aTwpfCEEQAxRGWQsbDkwVGk5eGAIXAwoHTxgCWQVBEksHV0wOVQUFEgxAcRlPUgEN',
    'DAscDllXQT0EARJOFwYdAxkMHA0ECgAaDQEKQUt+BQABDlVLQhcHSQMDB05JFhZcTD0NGh1LSwICBhhVX0wbVQ0FEg8LX1cJ',
    'AAMJQhsHDg0YEhYZBhxxDCkHBRoaGl8CDAYFCwxVMwUNTRMcBxAIDRAQCAAdGhpEFDAdAggLAQo0TgUABzcbEg0BGhsJKx4L',
    'RBAHBlZEKiYoI2g+NS8FKVxxDFZKTDUOC0MUFlI3JzAmOyJuLC0uNxtuQwEdCB4VChpIBTATCwEMDBZRcQNBUw8QQU4QHBkY',
    'HQYAF1cMGg0WAwwbDl9NCRIYVV1aDFUFBRIMTkAYABZMEAoAGgxFGRJdSzl7eys7LkwaBhoNIC47OC0sKEE3Q01BAR4ZV15Y',
    'KQdMVElOAFccGg0WB08aBV0fDh4bAVdJPhtJTFRJQw0VHRsCA0IAGAUNGQ4DAhZBcQxVSUxURE5DGBtSDQgVDhYYDR8EABsa',
    'XEkLGw5MAAZOWAQKADAKQk9PSwBNGBweVVdVCwYdTBEfC0NXGBoJCkIaHA5fTQgASxtdWUIYDB8HCAlEGQguAkRCT09GDSku',
    'UyU6Zg0VFAAYVBkPXgQGBAkIG08JBF9NFAAOBxJZDVUFCRUNMkMrARwNEBcdDgdyGQ4DAhZtRAwcHQUVHQdCGVUuAkRCCwoY',
    'Th8IAx8cXUNYVY3Uz4zkhZHg4oTL/4bN88nQ55fT+NW5/ZLIwCgHTg0FGh4JF1gzAUsNTUFeSwZaTBAQSQodGx1ZW08DGQER',
    'GwYEQ00IAEsaQlkLGgcNGDUADVdPUkFEhtfig4vshN3KnKWDh8nmivv5h7rZMxxMREJPQktYHgRTEhpHX0IaHgJUDBZdEh0b',
    'CQoBCk8fQk0NFgoREkQMAQZMAAELDQMAAgUHTk8BBFlNBB4bAUsNEwAMHwAAAUMEMxxMRAUAAA9yHQAHHxBAQxFPNQJUSU4N',
    'Wk8uToLq/orjt4r9+I79gsna9Y3U3ovuiytNUkSB6umL0YaI3eaO8ogEPhtJTFRJQw0rTZf68IvtzI6JxIjxyJGKh4bP4o70',
    'zzIPV0eV18mG1uSOpOCG6e+dnbCL1/FFKAdODVdPX0w4QInm68nWxJvEwdSl853O5ZHX+c/3yS5OREqH6MHK6deb1PLUlcNc',
    'NQJUSQxMEzACDRAWCh0FXlc9HUtVEg1PVTVOkNTOyczll8jNitDojpP6h/PlkYulhNXeg8j2Mg8rAVJMFA0GAR8XTSUBAgNX',
    'DQEaBxoRGx1MAwYdAkQWBx0EWAoJUxgdU18LGw5AVAcBWVcNC0wBGhsdCk4ZCB0MVUBIEQUGAgcMHXEZMxwYCxIGDDROAg8H',
    'AhtHTBYcBgJONQANVwsXHwcQBh8fRAIPSUuSiYCK2vSF1vGJt/OJ5NWB3uAzBQ1NEwYHEEEXPhtJTFRJQw0OAAdMBwMBTwlf',
    'BA8USwBCDRIHDBodBhteVxsdHA0BHE8KSxkEAUsGV1sHBwgAVB0bXxkcLgJEQk9PRg0DDgdLEERIEAxJGBsZB05XARcJABFP',
    'DAdCHhQBDlkSRBZVCg0aSQBMAxoADQgOFk8PXwIRUwobVg0QEB0ZBgcyQysBLgJHQU8uH1kIDwcCGlwNRFU7CQcZAUMEClI3',
    'JzAmOyJuLC0uNxtuQwMBHQkaHQdCGTAWBRIHHQgOQw4ESTcbEg0GEBoPBgAeWR4AHFZEFQcOHw0UDgZLFlNfB1UIDhscGg2V',
    '5tJMEwoOG0tYHgQBSxBfXQoUGgUODB1xGU9SHhEOChxRcQNBU0tVHw0BFAdMEgYNWARPHQJEFwEKE10IAgcOERJJBwEIBRg1',
    'AA1XT1JBRAEOAUtECg8cGRASWBEQG0sHSQNMHgFSHAsLARs3Q01BU0tYEk4DG0kcHR8BWVcbHUwLFQFPDlUdBAECEFxOBykH',
    'TFRJTgBXFh0ZFkIJBgdZCBNTBRpGDQwUGx4VHQFfVwsHGB0+AU9LSBUAHhsZVxc+G0lMVEkbXhIdLR8FGxxVS3FPh/v6kYqm',
    'h/jhieTqh7DViOjogvXZiuu0iv34jv2Cydr1jOPegNaQksLiMEY+AU9LDU0DEg9PEnFAnNHRkcT+yNLSl+PLhefehJHsh+vE',
    'kYmthszhhdb1hqTFiOjoi97wi9aNiNjAjeKEytn6jNTMjPKFnu3RifThhvLJyP32nNfqbg8+G0lMVEkJQhgLSDAKQk9PSw1N',
    'TFM3V9ei6pD57530zHFVMxxMREJPT0sATT1Rgs2PyM/lhtDrju+dkPX2hNv6iffEyvTclPHxbg8+G0lMVElODVpPLk6C6v6L',
    '0KeIxdqPzK3K/v6M5MSN1q2S4NhMjNTqh+mIMUMvBVUSDUIFBgUaHVQNBwYRB0QtISpLSQgVEgIZHg0PFBAOEUkAQgNPBx8B',
    'EEgcS0AMCB1LBV1EDAE1AigHBkIYBAEzCg0bMA9YABEAUSlcDUIRDB8XGwddAwYdAl5CiPryxP/IlsblEsna+I/024zuv5LB',
    '/kyA2u+L04eE9t2C16rI0sSMyOtJiYD+it3VgvTWh8SZMQ9TSwdHQQcGUzAaSU4NV0JSHwUbTyAlaE0VGwIbVQ0WHQwCVB4P',
    'RAMzHExEQk9CS0AMGVNZWAYNER0GHgBJA0gEHBMLAREzAUsNTUFeSxRBRkI6JylUGBtIBBsbAwpCAQAfDRkJAQ4QbkNCVUlM',
    'WUkdWRgfUg4BBAAdDg0ZCRweElpZQhYGAQQFC1kSHC4CREJPT0YNAQQSHRASXw0aBEwSBhwNAhwXHkQWAE8ZSB4RHAURbkNC',
    'VQsNEFNOUSsBUkxEQorK1sj94pb74t2R/ZPh/ZPl8svvwJfbw4fq5I6n9obp75CiikKR1MyQ0e7K7NuX+viEw82OmsqE9uCQ',
    'uLY+G0lMVEmKlfqHzeuM3faL04eK48qO5bHF+f6O3+FJiLTthtfBjN33ivuuiN/kj825yPLiNQJUSQlCGAtITDhAi9TrydTp',
    'lvrG1bfmKUswGjUAcRlMUUw3EgoKCEVNMRIfAVdfDFUyJD0uJnArAS4CFgccHwRDHgQsBhpWSFgpB0xUDQteFB0bHBALAAFR',
    'DR4UHgYUQEQYEEkCGx1ORAMKHwUeB0FPGUgMAgdLAV0NFBwLCVQHAVlXDBoJBwkDBhhZQz0dS1VAWA4QGlYoB04NV09fTAMH',
    'HBsKQRlBHB0QQA0SGgACAEkMVFcfHQUKFjMBSw1NQV5LGlxIQgcMDRcdB0IZTxEDEgcdHEtAGA0HAgVeSEIcBxwBHR1xGU9S',
    'TERPTxYEWE0FHAVSRg0NAgxMBgwdXRgBAQlEFgBPDlsIEwpLBV1EDAE1AlRJC1UWAgIAAVgzAUsNTUEGGBBAchEUEB9OSRJx',
    'GU9STERCT4vQp4jF2o7Jssne74HO34DEr5PV9DAKQk9PSw1NhvfdkKKjheHchPD4i6L/iu/jgNjpMwUNTUFTS1XXtvyQx9qc',
    '1vbJz+Sb98yE3c6OlcuFz/UpXA1CVUkOFQ1UDStNl9DkhtP1g4/GiNnpkJeQhPbBg8jlibnCh/b9gf/gi9GriO7cj86Xyd3b',
    'htD4jdamnvTaievNi9TOydTRl9frbg8+G0lMVEkJQhgLSEw4QIvW9MjJy5Xo3daX5FWN1/6MyoST0tIwRkJATzcPhez6N1cS',
    'AkIpS4jP6YqU/4nC2I3i6TNJcQM9HRkQU04WHAYCKw8HXwQbSDAKQk8dHkEIEkk3GxINQlVETBEEAVkeABxMBgcJABlITQIc',
    'BQFXQxYpB0xUSU4AVzNQifHogNP0cU9BL0mQpLmA9c+O9M8yD1czUIrx8zNNS3FPhOTEKRANAwZJAwQMAEgFMxxMREJPQkte',
    'FAwRBBkSTA4aBwlUBgVMDlVSg9j9T43ri4/h1UuajqyNyehMm9TwcRlPUkxET08dDkwOFRoEGxJOAxtJHwAIAElXDh4DCgcz',
    'AUsNTUFeSxNXSA5VHQQRB05ZHwYcB0QWBwoFDR4RFgoebkM+GxocEQwNRSgGHxwBEAkKCFkEDh1RKVwNQhEMHxcbB10DBh0C',
    'XkIcCgVJTRUbDhsSTg0HGwkXHUFMEwtcTBAKBgEARAMGUxwdW0EHVR0VBAAASlkzHExEEBoDDl5XPR1LVRINT1UAAhcGA10b',
    'CgYJRBYHAB5KBRVTBB5TVFhVNU6d8+HJydAuTkSA6f1LcU+Fy+adlKyKy8qL7u2LncaH0+A4QDMBSw1NQV5LBldDBlUdBBEH',
    'Tk4YHQAJBxZVTzcPi/n9jtGbyPLSNU5Ui+i/VzNQifHoi9fmyMLYU47lvMjG3DVOKAdODVdPX0wXBwELS1kFBB1LBkddEhkM',
    'AREHGhdXM1CK7POL1tvJ1+cvSVXQq/BVNU6c1vbL+9Wa2NGF9es3DzEPLwUTQEwFGAwCAAgaRBgBSDAKQk8dHkEIEkk3GxIN',
    'QlVETAcAAEobClIbCxALTwpBAQ4EDhFuQ0JVSUxZSR1dGwYGTBAKABoMRRlBEggHXV4RVQQJBxoPShIcLgJEQgoXCkAdDRYY',
    'T25DQlVJTFlJMg+e9cyK5MgzTUvP6/NTN1fWkMKd1vWQ0ObE7dGa0+M+TTMFDU1BU0ZVbg+H4OODyPYyD1eN9P5EPk2I97KI',
    '4PSM77ZxQCkHMBoMA0IDBh0CBQ4wHB9MGQRJNxsSDQYQGg8GAB5ZHgAcVkSKyP2DpN+H7+KdtYeHwtiL7u2IrvKIycaB8OOL',
    '062IxdpLkI+ch+bkhNXBhpPJiuDggerpi9GGhcb1g9KgDT4bSUwGHAJIBFUuAkRCT09GDR4OHg5VVkwbBkkLGwYKAVccHQEB',
    'QgsOEl5NAxIPWRJeDRgMTBAIF15XCR4NED4BT0sNTUxTBhpdSUIUDwoRChpeVxsdAgFOTwMOQwoVG0dVV0MHBw4VKAcyQysB',
    'UU9EMRYBH0wVQSgjPHVlPykHMBoAAFsSHQEFCwwwHB9fGAIHHgdXFz4bSUwGHAJIBFUuAkRCT09GDR0TFg8cUUwWEEkKHRsd',
    'WVccBw4OBwwbS0EMEgc3GxINQlVETAYMD04DBh0CRAQGHRhZTQIcBQFXVRZVCAoADBxxGU9STERPTzNJyMn+lvruEsXd7I/A',
    '1TVMDRkABkw4QIfQ8svBwJbP6te8+SlLMBpJTg1XQlIwRofA1o+W+47P9JCMpYfN0YTT6E7FyPaVy+mE7OqOq9g9UTcbbkMN',
    'GAAfBwABQ00zHExEEBoDDl5XPR1LVRINT1UNHhsZTl4CDRgJBxZPAAlHCAIHSxZdQwwQChgdHwsNAAcXAkQNDRkCQhgSLwVV',
    'Eg1CWEkwVoz+rpPV9DBGQgEAHw0xQ5Xj5Nea0JLS45H57cXI6JvJyYbV6TcPMQ9TS1USAEIBGxkHHU5BHhwGCQoHHU8fQk0I',
    'HQ0QQHEMKQcwGkpNDScaHA8QFw4bAkIDQSgoJ3t5KzYoICk1AHEZHwcCBxYaDh9EAg9JNxsSDRAABQkHUzJDV09STElCISo9',
    'aD9BBhgQEnFAKUtMGxtOcVUzUEwLEE9ITA0CE1NMUhJCEJbp4Jfp40wZFlIdEQ0bDh9EAg9TBhRARhEpB0xUSU4AVyE3OiEw',
    'TwoFSU0WGh8dEs7i9wYeVBkLXx4AFjAKQk8OCUIYFSwaAF1ZBwZTTJLq3cjL1Zrc54X0242jyInc31XWle+Q48yR1fvI+Ngu',
    'AjgMMwFIDk0nHBkXW0kGEAdMLyo8ZCMmMS0oPzMBN0MMFxwCEQhxDFVJBQAMA15NMxxMREJPQktcGA4HCgFbQgxVBA0GAh0N',
    'X4fz5oHGxovToIr1247Jp8jtwozQzoHerl4zHExEQk9CS0MYDBEOB1dJQhkAHwAaMkNXT1JMSUIJGgdBTQ0cDBxRTA5VCgQV',
    'AABeKwFSTERCQk8eQx4OHwIWW1kHEUkNEB8HThIzHExEQk9CS0sCEx4KGRJODRsHCRcdB1sSHC4CREJPT0YNCBkbCgBBWQsD',
    'DEwGDB1dGAEBCRc+AU9LDU1MUxgQXktPFgYCAAgHQxILUgELDAADBEoYBAA3GxINQlVETBkcAlkeHx4JRBMaChhZBA4dGFVd',
    'QwdVHRkGBzJDV09STElCM02NpfyG4+2dlY4+V0kwVo/mvJH3/Iv934vSy8r35ZXv6tei9SlLMBpJTg1XQlIfEAsJCUtEAxUW',
    'GQNbSBVVGBkRGhpEGAEBMAo+AUxIDSsTEgwYV0MWFB0FGwdOfgMWHglEOScmLGUwPR03G0FZEAAKGAEbCxcrAVJMFhcDChgX',
    'MQ9TS1USAEIYBh8ASRtDEwoATFZSTwwDTB8SLwVVEg1CWEldWVxOQBIcAQ0DBxxPG0gfQQceB1xxDFVJTFRETl4fAAAYRAsc',
    'Tw9ICwAGBwFuQz4bGhwVCgtyFhwtHAUXHApRcQNBUxkAXkgRTzUCVElODVpPARwFAQpPVg0dAAYYEAgNPleM+9tJi4jKM1BM',
    'OECK+uENhd7qjdWFcUApBzAaVUHL6++bx/yE4+iPlslfUUdXRl8LEg4JBiQBSRJNSE4UBx0CCkMIDwdJWRBEDB8MDwAAAUMn',
    'AAEFEAsAAUkXTxIKGAFXQD0RDBwAAUwBVRwLHxAHAisOXRkJUVFFHg8NBw0JBktUFE5WXk4WBwwaGV4EFxZJT1RMDgYMQFYM',
    'AEwVAxcIRlgbHR5IEE0ISRxWD1hXCxkdBRpEGUIcDRAXHQ4HAAkIEgcaVVgHV0VOAAAaQRJNSE6Mxf2H4p+F5tmM8YTIzcyB',
    'w+lLQg8cCgsbCxALTVEPT01RCBpcWQcbHU5OS1LF0P2a5daK6MWMqduE3NKdnbBcKQddWkmHrf6J+cWC4siK8LOI2+eEyajI',
    '7d+M9+qM1LmR8/uJyvyH28PI6+SWxczVt+adxvGdy/bO9+2Xw92KwPKOosKI6eSTpZuK8sOL8N+LrOuJ386L3uOL06CI3vaO',
    'yYjFw/mP7M+O1b6R5+SK6/KG+MXO7eMvBUccDYXp9ona94ip6IvK4oLX7orhhYvl7ITJqMjn9IHCzIzvm5Lf5oTGyYrf5MnX',
    '6pXi5tS7z5rV5JHP7MLL9ZXB7YbX5EvI7fOV28HWl+Sa1eWb1eLL//mV+NWH0vyOpOCJ3PackLWK8sOL8N+GrOOJ8d+B6t+K',
    '7puJ2uWPz7nL4fCM1cKN1paS5dqJ7OSL1cDO7eMvBUYcDYvo94ro04iPx4rp8oHG4oDXt4nZ/o/Ot8XA3ozm3Iz1s5DC5oXz',
    'zIbN88LR7Zbk2taWx5HR15HjxsXDzpXgyoXkw4yG5ofz9pKJh4H164T/zIiF1on584LiyorjqkKE9t+Ql6aF/9+K9OiBkfuK',
    '9+2MzNeJ9ayI5MWDyInI3NuO9vCP576SwuWF8PuKwvzO7eOV/sHWkPGd1tGS2OzIy+2UwcGB7+6Ct+KH88yWsqyH+9KK6NOI',
    'j8eK/vqD+OuI97KJ28mD9LjIxtyP6OuK7q8rAU5DjMX9h+KfhebZjPGEyM3MgcPpV0wBVRsABQMFCh0mQgkEUVFXQkgQGAgC',
    'EQcaD1tNGwIOBwwbAkIDMRwYHEZEDRtLVlYaF14DCh8zAAcfGwMPQUMAEgZGSA8xDBwAAUwXR0NQAxYGCh1JF19RQ0dXQEgB',
    'ABsfHR8LD00JEwAXB0NNDkMMAx8OERAXFgccCQlFFQ8eC1BWRgAaBgdZBA9eChtGRE8TBh4ZCBoAEx0dHElTQl9JAU8VGh8Z',
    'Vw9YV4D0xoHvp5LL24rq64nP18jR7kJFRRABQB4MFQMGHElVVVCE5eiKy8LC0e2U1dHarOia1eCRxtfF2PJQQEYBAAEfSAMV',
    'UVFXDsT6x4/i/Y/OkZLT/VI4DIrS+Mjk7JTl2teP4ZHR1pHN9MvH+5TfxYXkw4yG5ofL2ZOtvo3J5YjMzImL9ofM/4Hl1YfU',
    's4XV3ILgjcvR1Irs9jUAy9jgltTkhMHajKbBhtjgkJ2Uitr0j/Toi6ffi8/wh+LuiuSgiNvnjf2kyP7Pj/XbjOaqkeLQg9ju',
    'itDuxMzalODZ16DCkdHskNHEy8f7lN/FjdPjj5X5hcjukKKGU5HRxpHH4svi25rDyYbW5oit7z0djdq9y87UgcPZjdekku7u',
    'hcXdief9yOXmlebX1LrUmtXgkdbrxNbUltTwh+DFg67QhufDVW5xQp3W95zI4sr+xpX84ov1+4yL1o7P45GMpofT64PI84un',
    '34vP8Dg+isDSxcL8nNf51pXHks/tkNTRyuPHl+nShtT5jbvUhM/kkKKlh8zfg8jgja31MxyI3O+K4MTI/emW0sPak/GQ7tab',
    '1eLFweqb+duH6eqOg9SEzO6ck5aGzdKJ/sGIouWK98lEPjNPjabrhPvtlrKvisr0hPTshpPkivXWgvXPif6ljuHxNxsOAovt',
    '24r64IiNy4rO41pAQ00fXwQGFA4Hf0IGEEtWVgILVAAAAAhGTk0GBUcIAgcCGlx9DQYAGB0GAA9NTQEVFxYKAjRJCBEHA1ce',
    'DxEMGhgRBCpIBxsaTl5SQ00EXwkEAUlPAx1SWUseEQobXwQGBAlGWAkOB14ITVEOG1NPDhANTk4dHFgSEl4XRgsLTVEPDxQa',
    'BwFbQ08bBkEHBQtIB0ICGRcKBgEMAB0THB8aUUIOV0VOAAAaQRJNSE6DxO6K6YGK/dOO+L3FzNtLQFYCC1QAAAAIRlhNiPaM',
    'hcb6hMm+yN3ejvHVS0IPFAAcGAEMG01RD1GG1eqQsIGF6clSKAeKkNeK/caC+sCG8oeJ3ceD9bfC3vmO1+mMwZST1/+J682L',
    '19DI58mW6dnWkuGQxtWS/9fK6s6ay+2E5/mOlN+HxeKRj7GE9MaP9OsyQ0VcSFxUh//hjbHthNfxnY+WhPr5iMzpiIHWgM7g',
    'jOnKisSUi/fKjf6gytnoj+Tij+2ekOneicD+gNPnyNLkmsrO1LrCk/TNkNLYy+PAlODlh9bZgqjghOPjnbOnh9HAQ5HB38nO',
    '/5Hs5j4Bi9OIisfyjvSXyNjCgcPAj/u0lO/zifDCiuDDy+X3l9DO1pD3ksfNkcfYyMvglfbghcHOjaPKgvPpKVwRTZLP7ZHr',
    'wsrrz0xOSEAbHQJKCgQBJhpWSEBPSwcREBlCBQtQQEYLAQUOThkIHAUlXV4LAQADGktUDxUKFAMWBzAdBEEIQ19JBkteFhAE',
    'KBEZGkVVVUZARg0dCw5fT1tCW0UeDxAQChkGGgdbEk1ICgUOHApHDwgPEgkZV0lATx0eAQwTAQxNGwhGWE0NHkQBFRoFWEJY',
    'DBYdGRUdB0IZQgcfBQUKQhlYAQQASVkQWQsBBQlWU0zL1+iV7t2Fw8mOotqFztSSpoWK0u2J/PBMAVUEFxUTDR0LSRdPQ19J',
    'Fl1DFhAHGFZTTBFYidLrg+DWiMeLiO7Ej8iNyvbdgcvwjOa0STMcTERCT09LDU06IBIGRkgPVSACBx0cWBQbGwMKWE89DkwB',
    'CAAfHFENLxoLBRgMTm4fDgYYDQwITzhZFA0WNilcdA0ASSEhOjoNBAYfGQgDGwpLTE0TFgoZW14WHApAVAQBSRIdHEwKBxsG',
    'EUgDRgBLAUtdCxsOTBwIDEQDHFIKCxBPFBBOBQABFggSRAxVCAAYSQNIBBwTCwERQTMFbAkJFhkQElkNVR0EEUkIQhsDHRsN',
    'DAhPDUIfDBIfAVtDBVUbGRgMHQ0EGwAFBxYDFktZAkESHRpbSUIGBhkaDQdDEE8AAwYNGwYIFzEPLwVEHA1IXycjVCwgaT4h',
    'NUw0Jz0mJGk+QVstGkBPCxENCRpAVAddMxxMREJCTyVoOyQhSwBBSEIUSQoBBQINBBsdHEQ+TYzrrzFDUwoBElkKEEkJGg1O',
    'QhFPE0wJBxwcCkoIQRwZVUFFDQcdTAcMAFkSAREJF0xPJh8NCwQWBwYSWQ0aSQobGwNMG08TAgBCHQYMRAlBFQQHEk4KFB1C',
    'KAdODVdCUikcAwIfB0hXQS9Jk6+Ihs/vMFZJRmoYABZFRB5PM0nL8MSX0fPRreApS0xcKw9JXjMcTERCQk+Mi+yG58OQvYiH',
    '+t6Lz/qLncmAzvaD/cKK5IiL/diOxYzJ2tCOyvWN05KQ+9qO5P6M7+nP7fyc1/nbsPyQ0dSR6tvK1sOd0OyG0eSEkfeE/Pop',
    'EMv/0I3W8jVMxffjltTphPfANw+L/NaPz7TO4vc1TpvV58737S4COAxdQUsHRzIjKjZ3fkI6PykmSS1iOiIzP15IRTMFDU1B',
    'XkszXV9CBgEDBh1OXRYaAQkXTk8aGEhNS1k4BVNOBwZJMFZJMg9dRVIFChEbCgpJTQ4VSzZdQA8UGkwoS4GR+zNQQjgMT09L',
    'AE0uHQcMElgREEkPGwQDTARPBQQBDE8bEl0EDxRLEEpZEBAECRgQTkEYARVMFAMdDgxfDBEbGFVdX0ITBh4ZCAINFgEcAxEM',
    'DAoGSAMVAEUpXA1CVURMMREPQAcDF1ZEPk2L06CExMxLkLelhs3kieTqMg9XRzUDCwZGTxcNMUOX0/jbiN2a1eCR7ObJz+KX',
    '/Oc+TU9DbwwFWjcbEg1CWEmL3dOIjcuLyc+C+dCG67qI7sSEyajK/diP9vaM77Gezs2J68iI+8PKxNuVy8ndke6R0umd/NHL',
    '2dqa/NmH4MCMucWI8/yQvZqNyeGIyuKBke2K/f04QIvX5sTI3lOO8LrJ2viM/Pc1TMX345bU6YT3wDcPidn+gtCNwt75jOn8',
    'jdagkv/xMEaN0+aIre89HTcbAQNCX0MiO0k/eDg7MzgtLSFPJmw/KiBLXWFZEBwKGFQ7G0ESRkhGTj4BT0sNQEE9LiN3f0IA',
    'GglUGgdDEAMXTExFT0hCDQITUw8aR08OEElEKEtOcVVGUh0RDRsKGA0ZDlMOGEJFAwYAFhFJGUIFCwFMCxBPDAJZCEEEAxRG',
    'DQ0BAQkGGk5eFgYWQkQrG08HQgIKAEsAXEMDARweFQVORBlPEQ0XFw4DS04FAAdFKVwNQlVETD4cHVlXGwscAUIbBw4NGg4B',
    'DwYSSQsHDA8ABRcNAAYGBAsXG08PSA4OAQoBW0IMWzUCVElOAFcqCg0JEgMKUQ0xQ5fW1dqC1pLz6J3rzcnPxZTD8Ira9DcP',
    'TUk0BBpWBEIJSTBWjdONn8DGi/7mhu3IydXLkevt1IL2ndz3lun3cVVPWi4FBkYzBQ1NQV5LkpSsheHBicj8i6LAgM72gNrK',
    'iM2sidzMjOGayO/gjOP4jNK4kuDFhNv5h87nyNHbm9v21KX0kNX5k/3GzvftLgI4DFtBSwdHMjolMn5oQiYwITYmIg05OjMi',
    'Jyc8T0N+GQAdDxReQgwQST4RCA1ZHgAcH01YRUU3Q01BU0ZVbg9dKUtMTkk7XhJPEwALDApPH0JNBAsbB1deEVUaBBsKBQFX',
    'DB0CAhccBgRDQUEXAgZQSA4cDApYSQFfVw5SCBYDAg4fRA5BL0k9R0VdKUtCKAdODVdCUjBGge/tNw9NW1M+BlcNAxkGAhFJ',
    'GkJXCgocFgccHEteHQQWCB1eSBEGBwkHGkINFhgZGwUQC08YRAEEHQgQHg0NB0kwViBORRYZF0wKDU8YBF8JEi9JW25DQlVJ',
    'QVQ1TANZQVxCSj5NT1ENOBIWSxReQgwQSRgbSQtVBx0XHxdCDQoCQwpBHgQDV0lOVQEJGBkCSAQcUh8NDgoBCEhBQRwZVVMN',
    'DhoHC1QZD1gEClwwCkJPT0YNiOzmjtily+Hwjtfegc+Fn9HMg9j4iuL+yOLwL0majrI+V4HN3I7Kl57z9Yrn6ECI/byL4uKE',
    'yanI7+CM4+U1TM737S5OjMPHiM+Xi/bTg9qfwt7ujOHhjOG8K02Q7MKA78k3D4XA24zRiMvQ/IDX7EaIqeiK+MSH4u0zBRFC',
    'h9PskrCUhdnPifveipDIiObEjMXriuO0U0NfSQFARAUSDB45BgpIVVVQHAEQAg4FSAMVUUdXW0MIEAoYHQYAfRgcGxgNDQFN',
    'UQ8eGAAfEF9yBhAZGBxLQg8EFgEYAQ8rChtZBUNJX1kQQhARDB5WU18dR0NQHgEBGh0YRBsEUVETU0EREEVOEQcPTxsKFk5e',
    'Fh0aDlBBGlECERAXQBccBRgdB0NaAAQJFhAGCw4AAQgeAgEQAUABABgYDEwXVYjS2I37/01HDwYEChwaQElAT0tOWEsNQhkb',
    'FwIQQFVNV3kiMSwkI3d/MDwtKVQdB1kbCk8wRiMtPCRhODU2Syd9YjZVICI9PSdsOyYoLTArICE3D1NBUzcbDBNcVTo1Jz0r',
    'YFcgJCk2MCYrLg1XQSM5PH9oQjQqOD0/L3k+IDxMRD4BNDtFDBIWS0RvDTIAGwsdBwkNBQoBBQAXDgNLTgIPAB8HU0QMARpM',
    'lunIz/fJUi8rLz8jLnkoQVM3G2l9ChQaCVRbMw0lCgEYCxAGAQwNLg4BDlVzWBYdBh4dHRcNJBsTDw9Cje/Nz+3HUyg6f30u',
    'MD0pVEkyQyw/Gg0XB09cNg0sDxADGkBEDBJJPjsmOg0nPTs6LS4qKC4Nj+fhSzBcWQsBEFZUKgFABw4cBQsMTywEXwhBWyQH',
    'W0oLG0kDEkktQhofEwINDQEcA0QdSFNLKVxxDDQlIFQsNnkyPTwtKEIpJid5KDMgS0gSaSsmKC44LCoNVzMcLSguTyIkfywt',
    'Uyo7dg0xNC8pIDBOYT4iOzg3QlJPJXghLVNLKVxlNzgoIlQgIHkyISZMWUI8ICdoTSU6OTBxeSsjLExUNQBxGSoKCQcXGwYE',
    'Q00nBgUWRkQNG0lWVCYYSAUdGwgBSgdGSxBNJAsbFFxJSh1FTA8HAWseAwYJFlheQ0tfCAcGGBReF1JZSQ8RBx1CBVVCQEQB',
    'AAIbQQgVFlFETwRCVTUCJxAdWRICUiEBDwAdEg0eBAdLAV0NMjA7Pz06Omg5O1IBCwYKQUsNMQ8yHBRbWQsbDkwEGwdAFh0L',
    'TAALHQoIWQQXFksTQEIPVSEZGQgAA1dPLgJYTTsgO3IiNzY5J3tpJ0s1AigHT0oFDhwYRBIdBh1EAQQUDk8SXw0aHUxUNQBZ',
    'Fh0VCRBYTywEQB0AHQIaXA0hGhsJVEEhXx4IGwJEDQlPKEIAERIFHF1DER0AHF1JTnEZChQKAQEbVUtJBBISCRlXcgMZBUQH',
    'CAhIAxZeTBYHCRoYTAFNUwgQXF4NBxoEHRlCDRoAAA0ICxsWQg2P5+FLEFxMABkMRBIcAkEoDgcYDA0dBh9UQUEDGRxfTA4q',
    'AAIHHQdDFBtbTEQ+AQYFWQgGAQIBS3IBHQwPH1NOfTY8ISkgQk8zBUwYFRsEB1tXAwEAAxo2HVkWDBlWRDE2IShoKUFTNxta',
    'SAMHHQ4RCBpyGwYcB15CPDsqbyEkU0spXF4WFB0ZB1NObDQ7OzohPgEzBRErND0oIXtiLColLS0sPBNXTy4CR0IsIDloTScm',
    'JTZmZC07SVZUOTxoJCogOiFCrdhLbiIsIycwZmhCVTUCKAcqSBEGHAlEJEcHQhdNQS8FVRINQjNJUVSn1UVXjfT+REo/HQ5e',
    'CBMFDl1aBEKX4/lUKgFABwMXGAFKB0ZCDU09HUtVEg2A8/tMMQcdWAUKAUwBFAodEg0lFB4KGxJJCwcMDwAAGEhXBgFMFBAK',
    'HA5fGwQXR1VXVRIUBwgRDUINFgEWTAILAQ4HRBcEF0scXA0EAAUAWklOcRkzHC8LDBwbGUwEDwcYVRpkDxgcGBULAkheVVJM',
    'OAxPT0sNPwQVHgZTQUodQEyW7/wNJDYhOCEvTykqeCE1U0spXA1CVUkvEQcdQgUcGgUUSgdGS8/r81MvNGZsQjYmPiY8Pnk+',
    'IDxMRD4BT0sNTTUBHhtRTBYcBgJcAUcNlengTCknIiA5dE0nISo2ZngwMElMKAdODVdPPQENERwGBENFCVpLl7S/QjQ7Lzwg',
    'OGhXIz0/N0JPMwVxAzMGBQFbQAdVLAISBhxOEgIXAhBYT083Q01BU0s0XkFCFgYCBx0cTB4BBkwSCwADClkEDh0YVUVEDhlJ',
    'GAYACUoSHVItERYAAgpZBAJTORBFXwsBDEwkGwFZGAwdAERKLj07BENBUzcbEg1CVSg+JElTDSUKGwIXFg4bDgUrSRtCXBJY',
    'DAEAAFQKAUAHAxsNCgEKT1YQTVBDW1AcDUIpB1BbLztjNDs7Iyo9Iy4yaD9fLwUpXBELEQwCAAAaVEkzHE9EMAADDg0+Fhof',
    'FloXQjYGAQQIAEQYAVIvCxAKMwVxAycBBBgSQw0CSQMaRU5LAgMeFUQQAAMOXQEACksUQQ0hGgQcFQcHQhlPMQMWB0NPCg0Z',
    'ExIFBlFIDBEMAgBJDUIaHxMCDQ0BTw5DGQgHElVQQhAbSQoGBgMNFAAHAhAOChwYDQ4AHwcGEkIEVQUDAgxCDRQAHxwFDAYA',
    'BV4FCANHVVNDBlUdCRoNC18ZCgEfRAQdAAYNBRQeChtZRAwRR0xUNQBxGSwdARQDAQYEQ00iHBkQEkkNEBpMGgYaDRUKHgMK',
    'BU8bBA0MDwpLGFNZBwcADRhJGUIFAxZARAwAHUtMDgodBAJeSAYSDEwcHANMGU8eDRMRQ08GQh8AHwIBSwFCEB0EHQodAVcA',
    'AEwWBwgaB0wZCBwFBhLP4uFJGBwMFw0WHRdMCQcOAQJDCg0WGAYSTAwRSQ8VBwBCA08eBQkLG08SQhhPU0spXHQNABtMGwcC',
    'VFcGHB8QCwEMHw0MDxdLHlxCFRkMCBMMTk4YAhdMAhAAAktZBQRTCBpcWQsbHAUAEE5CEU8RAwkSDgECQgMSGwIFCA0DVQoD',
    'GRkPQx4AHEwBDBsGH1RNCABLFl1AEhkMGBFFTkwCGx0CCw8AGhgBTQAdD1VUWA4ZEEwXBgZIBQocGEQLAU8CWR5BHBwbEksQ',
    'FAQJWklOcRkuHgBECBoLDEAIDwcYVVRCDhkGG1QKAUAHDhwFCwxPHB9MAwUSGRFBAUIbDBoRG05LBQ4VAQEMGwoPDQIUBxgc',
    'VkhCFBofAQQeWR4AHB9KQk8zBXEDg/P/l7K5gfX5KQwAHVkSAREJRC0OGwPO7fCR6+HQrfZVSTAaPQENBQoUGRcHTyceQAwP',
    'UwIGElkNVQweFRoLDQ4ABx4XBwMJRQ1NPR0/GhJOBxsaAwZJB15XGx1MBw0dHR5dGUEHAxASSQsDAAIRSQxCGQtcTEQ+ATsE',
    'DR4ACkuXsrErVQoNGgcBWZXv70wNEU8bBA0eCRIfAVdfQgwGGQZJAVoZTxAJDQwIQUsNMQ8qBABADREaBQlUBAdeBAYdAkQL',
    'HE8fQk0VAR4GRgFCGgsJDUVOTBkLUgoRDgkGB0FNKQYGFFzP4uwaTAMAAkFbTwUECw4DFktMAwVTHBxGRQ0AHUwGDANMHgEW',
    'CRZMT083QzEPkevh0K32lun8IAwNRRkGEQ0IQj0aB0iO4eKJ9abP4uFJTCgHLEgRAAAJRAcZChlUTQ4GHwVHWU5VCBkABgNM',
    'AwYRDQgOFk8PRB4CEhkREkwOGUkeERoaXxYGHBgXTk8cEl4ZBB5LGVtACwEIGB0GAF5bTwENAgcbFktLBA0HDgdBAUIHDAoB',
    'Gg9BBENSGwUQAQYFSh5NUwQHEl4HGQ9BEREeQRYBExgNDQEcRQ1NPR0qGUVMGwZJCQwZD0MTQ1IeARIOBhkBTQAdD1VRQg8F',
    'BQkADE5aHw4GTCwXAg4FDQoIBQ4GElQNAEVMEREeXxIcAQUKBU8GHw0LFB8HDBJMDBFJAB0dC18WAx4VRAMcTxtMHxVTBBMS',
    'WQoQSSkADBxDFgNSLgsMC0FLDTEPOg1VRl8XGwoNAAABQ1cAAEwLDwYcGEQCD1MEFlFYEAZFTA0GGw0aGgEYRAMaGwQADg4d',
    'HxxcWAdVHAIAAAINPxofDQqA7/YYDQ4OHgYUXElCHBpMAwEBQRJBUkw4DDMBia35g/P/lrK9IxcaAxgcGkhXPwAFCxAGGxLO',
    '7fCR6+HQrfZVSTAaWEANPxofDQqA7/YYDRoIHwdVU0MGVQoDGQQPQxNPWhcfFxwKGVAQSF1LVW5DUFtJNRscHA0SFxsfEAcB',
    'DA4NRQ4dBwwSWQ1VAgkRGU5eEh0EBQoFTyceQAwPWkVVEnEMRkdMMR8LXw4bGgUKBU8KB14IQU5LG0dBDlUIAhBJGEIeC1xM',
    'RD4BMwXP7fWR6+HRrfI8DQkaHQdZDk8/DRQSBgEMzu3wkevh0K32VUkwGovusT8aHw0KTo3v9g2P4e8+BldfTpfp8VQIAElX',
    'jfLwNgcOCw5fj+HuSxReWgMMGkwVBwoNGAEeFUQPCg4FDRYaBhgQQFAfW0lMKAcgSAEKAEwHDQEJHl4IQRwZVUFdDhwdTAAB',
    'C0BZT1IwCjsAGktIFQgAH1VBQg4QBRVUDwFfVxQJGRcHHRIWAU0AAEsBWkhCGgcJVB0cWBJPEQMJEg4BAkIDT1NLKVxxDJfp',
    '+Jbp+s73/zcYARABDgcNIQAEiPWjz+Lhi+zgSU5xGTYdGUQVBgMHDQMEBQ4HEloDBwdAVBsLSwIcF0BEBgoDClRBQRwZVVZE',
    'DgAdCVpJTnEZNh0ZRBUGAwcNAwQFDgcSXgcZD0EFHAteAwYdAkQNHU8KXR0EEgdVRkJCGhwYBwAKSFcOBxgMDR0GH1RDQVM3',
    'G2tCF1UIHhFJDEICARZMEA1PDARAHQ0WHxASVhkAGgkGFBPP9/YBTAEUCh0SDR8EAh4QQVlOVQABGQwKRBYbFwAdQg4BDw0M',
    'AwAEGUdZBxkQQFQeB1kfTwYJCgYKHQVIHhJfSxFXWw0BAAMaRU5MGQtSGAsWDgNLQg8EFwIQXE4HW0lMKAdSAh4LFwIQCxsW',
    'VXEDPR1XJUBEFBwFCRMMI0ITClIYDRYDClZxTyAxODp+eDYwSTwmIDhkOyo1KThAUU9LcQMiHAYFU0MLGgdMNwYcSJjT/orJ',
    'xorn0MnQwZvJ3tSj6pHT5JL17sTc95Tx54v2/4it70FTNxvUpOKT9eWS9MvF8MVSJBEPDgFLwtHpCBAAQUgQCBSDyOCJt/OJ',
    '/uuA2cuI8auJ2cmMzq/IzcyP3+GN1YmY0/6J2+eGztDIw+2V/sHUpMWdyOCX6ewNVzMcMAqH88eNgMmG+d2TsqyGzeKDyPNO',
    'DSsBkOzwQj0KDVgeAB9LSBJhDQYaTBsPTn4SAxRMRD4Bjeu5TSIWBQZdXxEdABxUVE5vGAEWTCcNHR0eXRkIHAVVEnEMl+n4',
    'VCYDRAQcGwMKQlJPJkgADgESVXRfAxYdGQYMTg0rAZDs8EI9AAdBDwAQAFUPDSQaGw4dDQpIGU9SMAo+AYnirYv9+oPKtcvZ',
    '0Y3U+ozAjJHw14rMw4ry/Mja05bq6dW5yprV91RJMkOT1/KJ7OWKy/3E7smbzPHXpfuR0eKQ09TKxtSb7feH0diMl8uH7vSQ',
    'hZ+HyPuF79+NrfVPUjAKPgE9BEIZQTIeAVpCEBwdFVRUTn0yPT8tKichO0sNMQ8jGRxERA4QDglUOhpMAwpSUUQuICwgaClB',
    'UzcbQl8LGx1EKEshXx4IGwJEIQAdDg0BCAAfEFxEDBJHTDUeD0QDBhwLRCoaAgpDj+HqGFVaSAMHHQ4RCBoDK01bTEQ+AVNE',
    'fR8IBQIZV0oHOAYIEVcyQysBTi4rNjsgJnIiNzY5J3tpJ1UdBQAFCxArTTEDCRIOAQJCA0EwBAdXDaDCST8RBQgAJBoBGAUL',
    'AQoPDT8OHB9VcUIQEDVOSklOcRlRTFJEKyEmP2QsLToxPHxqQiYsIDJEPn8+OTsgISUqTzt/IjU8KDp+DUIpByIbSR5fHgAA',
    'TAgDFgoZXk0FFh8QUVkHEUdMVDUAbgUKExgNDAhPGUICFVMKG1FFDQdJjvTPTmI8T1IwCi0ZChlaHwgHAhtVDQsbAQkGABpI',
    'E08RAwoRGx0KRAMVAEuXsotCOiJMVDUAcRkrNyotLCpPKEIAERIFHF1DIRobCVxAVA1XMxxMREJPDh5ZBQ4BAgFLDV9VNU4m',
    'JiF5K01STDgMT09LDR0TGh0cXkgFEDYfAAgaSFdSUjBGIy08JGE4NTY3VxINPhtJTFRJC1USDAcYDQ0BMAZCCQRTVlVuDyw6',
    'Nio9JTpoJU8OTCotMD0uazgyMidVTg0sOjYvMSc9YiUzUExEPgFPSw1NFhsCGVcNNgccCU5JTnEZT1JMREJPT0tdHw4QDgZB',
    'BSoABA0aIABZEgEGRURCMwFLDU1BU0tVEkQEVR8FGwUPWR4AHDMABxsKCFkIBVtCTxINPhtJTFRJTg1XT1JMREIOGh9CMhMW',
    'HAdbWQddQExUSU4NV09ST0QQCh8KRB9BEgUMEl8HExwfFQVOAlcMFwIXDR0cA0QdQVM3GxINQlVJTFRJTg1XTxEDChYGAR5I',
    'TUEvBVUSDUJVSUxUDAJeElVSTDgMT09LDU1BU0tVEg1CBRsJBwwcWxJHOhkJAwEmBVkIDwdCVRJxDFVJTFRJTg1XT1JMRAAd',
    'CgpGTUEvBVUSDUIHDBgBGwANK00hOCU2KlVLbC8yPCcgZmg9JTslIiAiaDAqLSArISQqL3FPQVM3G25DQVUgITk8Omw1IzdM',
    'JishKyJjKjJTSylcfwcTHB8VBU7P8f1SIAsRHCANfggNFUNcEg0+GyoJGhoBXwQHGxxEgOn9S2gADgcCGlxpBxYIFVxATg0r',
    'AT0BDREcBgRDTYP1+VVwQgwRLx4VChpYBQpaRURCMwE5QgENEQoWWQ2A8/tMMgYcTx4LFgkKSkZPS3EDPR1IVXRkLDQlTCcs',
    'L2FXTy4CLBcCDgVkAxUWBQESEEImBgARJQ9aX0ZSTDgMPQAEWSwUBwMaQEQWDEEvGwQeTBkGHQInDR0KQg1QQTIoIXt7J1VJ',
    'MBoZHEQZG1owRi0dBgxEA0EwBAdXDREBCA4YDEANOwYBGAEMBgEMDQsOAUs9R0ADG4vs7RpORRIOABgGBw4bRXFPSFNLKVwR',
    'TTcmOCAmI3I4OTc+NisrKlVxAz0dDxBUDQcbGhkGDDFLAgMeMwsXGx8eWUUVFhMBGxc+G0lMVEkZRR4DF0wKDRtPBFgZEQYf',
    'KltePRYGAQQFC1kSRwYJHBZGVTdDTUFTS1USDUIWBgIAAABYEjAdGRASGhtDBDEPU0tVEl8HARweGkkaSA8bUEBGFh0GDEoI',
    'Ez4EEVcPWFcZCQYED0MSAQZOSEAGAQFIDhUaBBtiQhEcHQUbB0wXVRwLHxAHAjAPSB0VG0lZEF4bBh0JGS0LXQMHUFZUTk0A',
    'GUkIE1FRQAIBQAcMDwEbHUQBClBWAgMDHA4BTwQdChdeSAZXUxgGHAtQKg=='
].join('');

function decodeBuiltinWorldBookPayload(payload) {
    try {
        const keyBytes = Array.from(BUILTIN_WB_XOR_KEY, char => char.charCodeAt(0));
        const binary = atob(payload);
        const bytes = new Uint8Array(binary.length);

        for (let i = 0; i < binary.length; i += 1) {
            bytes[i] = binary.charCodeAt(i) ^ keyBytes[i % keyBytes.length];
        }

        const json = typeof TextDecoder !== 'undefined'
            ? new TextDecoder('utf-8').decode(bytes)
            : decodeURIComponent(Array.from(bytes, byte => '%' + byte.toString(16).padStart(2, '0')).join(''));
        const entries = JSON.parse(json);
        return Array.isArray(entries) ? entries : [];
    } catch (error) {
        console.error('Failed to decode built-in world book entries', error);
        return [];
    }
}

window.builtinWorldBookEntries = decodeBuiltinWorldBookPayload(BUILTIN_WB_PAYLOAD);

window.getBuiltinWorldBookEntries = function() {
    if (!Array.isArray(window.builtinWorldBookEntries)) return [];
    return window.builtinWorldBookEntries.map(entry => window.normalizeWorldBookEntry(entry));
};

window.getBuiltinWorldBookEntriesByPosition = function(position = 'before_role', contextText = '') {
    const entries = window.getBuiltinWorldBookEntries ? window.getBuiltinWorldBookEntries() : [];
    return entries
        .filter(entry => entry && entry.enabled !== false)
        .filter(entry => entry.injectionPosition === position)
        .filter(entry => window.worldBookKeywordMatched(entry, contextText))
        .sort((a, b) => {
            if (position === 'system_depth') {
                if (a.systemDepth !== b.systemDepth) return a.systemDepth - b.systemDepth;
                return a.order - b.order;
            }
            return a.order - b.order;
        });
};

window.getBuiltinWorldBookContext = function(position = null, contextText = '') {
    const positions = position ? [position] : ['before_role', 'after_role', 'system_depth'];
    const chunks = [];

    positions.forEach(pos => {
        const entries = window.getBuiltinWorldBookEntriesByPosition(pos, contextText);
        if (!entries.length) return;

        const titleMap = {
            before_role: 'Built-in World Book / 角色前',
            after_role: 'Built-in World Book / 角色后',
            system_depth: 'Built-in World Book / 系统深度'
        };

        let section = `${titleMap[pos]}:\n`;
        entries.forEach(entry => {
            section += `${window.formatWorldBookEntryForPrompt(entry)}\n\n`;
        });
        chunks.push(section.trim());
    });

    return chunks.join('\n\n').trim();
};
